[package]
name = "tenx-svr"
version = "0.1.0"
authors = ["Abilio Esteves <abilio@dotslash.software>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
reqwest = { version = "0.11", features = ["json"] }
